#!/usr/bin/env bash

FULLPATH_OF_HERE=$(cd $(dirname $0); pwd)
TOPDIR=$(dirname $FULLPATH_OF_HERE)
CREDENTIAL=${TOPDIR}/.cache/credentials.json

PS1="\[\e[1;33m\]\u@\[\e[m\]\[\e[1;32m\]\h:\[\e[m\]\[\e[1;36m\]\W$ \[\e[m\]" \
  AWS_ACCESS_KEY_ID=$(jq -r '.Credentials.AccessKeyId' ${CREDENTIAL}) \
  AWS_SECRET_ACCESS_KEY=$(jq -r '.Credentials.SecretAccessKey' ${CREDENTIAL}) \
  AWS_SESSION_TOKEN=$(jq -r '.Credentials.SessionToken' ${CREDENTIAL}) \
  AWS_DEFAULT_REGION=ap-northeast-1 \
  AWS_DEFAULT_OUTPUT=json \
  /usr/bin/env bash
